### ISSUE TITLE
what the usage of actionDelay?

### ISSUE THREAD

**Issue by sijiaxu** [TimZaman/dotaservice#45]
I'm curious about what type of action need some delay before executing this action?

https://github.com/TimZaman/dotaservice/blob/6e91ff15b25c53b7457e0f711ddb0de3dc5b54d6/dotaservice/lua/bot_generic.lua#L70-L78

**Comment by Nostrademous** [comment]
@TimZaman he introduced that to allow bots to do delayed actions (currently not enabled or used). The reason is that we communicate with the bots every X frames (depending on setting). So when we tell the bot to attack a unit he could do it immediately, or wait 1 frame and do it, or wait 2 frames and do it ... after 5 frames (if that is X) we send it a new action to do.

The code supports this, we just don't currently use it.

**Comment by TimZaman** [comment]
Seems super hard for the bot to learn to i didnt use it in my model

**Comment by sijiaxu** [comment]
ok. I got it, thanks!
